Add frontend testing automation

diff --git a/.github/workflows/quick-testing.yml b/.github/workflows/quick-testing.yml
--- a/.github/workflows/quick-testing.yml
+++ b/.github/workflows/quick-testing.yml
@@ -5,6 +5,7 @@ on:
     workflows: ["dockerbuild"]
     types:
       - completed
+  workflow_dispatch:
 
 jobs:
   build:
@@ -17,6 +18,14 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
+
+    - name: Set up Docker
+      uses: docker/setup-buildx-action@v1
+
+    - name: Install Docker Compose
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y docker-compose
     
     - name: Set up opensearch directory
       run: mkdir shuffle-database && chmod -R 777 shuffle-database
@@ -94,6 +103,103 @@ jobs:
 
         echo "User registration failed after $MAX_RETRIES attempts."
         exit 1
+
+    - name: Run Selenium testing for frontend
+      run: |
+        SERVER_URL="http://localhost:3000"
+    
+        declare -a Routes=()
+    
+        if [[ "$SERVER_URL" == "http://localhost:3001" || "$SERVER_URL" == "http://localhost:3002" || "$SERVER_URL" == "https://sandbox.shuffler.io" || "$SERVER_URL" == "https://shuffler.io" ]]; then
+        Routes+=(
+            'homepage'
+            'home'
+            'contact'
+            'workflows/fa9314a7-bb9b-4b41-8885-1d02b199f04d'
+            'services'
+            'debug'
+            'creator'
+            'articles'
+            'partners'
+            'pricing'
+            'pricing2'
+            'training'
+            'professional-services'
+            'detections'
+        )
+        fi
+    
+        Routes+=(
+        'workflows'
+        'workflows?tab=org_workflows'
+        'workflows?tab=my_workflows'
+        'workflows?tab=all_workflows'
+        'usecases'
+        'usecases2'
+        'getting-started'
+        'welcome'
+        'health'
+        'docs'
+        'settings'
+        'apps/new'
+        'apps/gmail'
+        'apis/gmail'
+        'forms'
+        'apps'
+        'apps?tab=my_apps'
+        'apps?tab=all_apps'
+        'search'
+        'search?tab=org_apps'
+        'search?tab=my_apps'
+        'search?tab=workflows'
+        'search?tab=docs'
+        'search?tab=creators'
+        'search?tab=discord'
+        "admin?tab=organization"
+        "admin?tab=users"
+        "admin?tab=app_auth"
+        "admin?tab=datastore"
+        "admin?tab=files"
+        "admin?tab=triggers"
+        "admin?tab=locations"
+        "admin?tab=tenants"
+        "admin?admin_tab=org_config"
+        "admin?admin_tab=sso"
+        "admin?admin_tab=notifications"
+        "admin?admin_tab=billingstats"
+        "admin?admin_tab=branding(beta)"
+        )
+    
+        ALL_ROUTES=("${Routes[@]}")
+    
+        cd $GITHUB_WORKSPACE/frontend
+
+        docker stop shuffle-frontend
+
+        yarn install
+        echo "Starting frontend..."
+        BROWSER=none yarn start &  
+        SERVER_PID=$!
+        echo "Frontend started with PID: $SERVER_PID"
+        
+        echo "Waiting for 1 minute to ensure the server is fully up..."
+        sleep 60
+        
+        echo "Server is up! Starting Selenium tests..."
+        
+        echo "Starting frontend tests..."
+        node selenium-test.js "$SERVER_URL" "${ALL_ROUTES[@]}"
+
+        TEST_EXIT_CODE=$?
+        
+        if [[ $TEST_EXIT_CODE -ne 0 ]]; then
+            echo "Selenium tests failed. Exiting..."
+            kill $SERVER_PID
+            exit 1
+        fi
+        
+        kill $SERVER_PID
+        echo "Testing complete. See above logs for errors if any."
 
     - name: Get the API key and run a health check
       run: |
